version: '2'

services:
    mysql:
        build:
            context: ./db
            dockerfile: Dockerfile
        networks:
            custom_net:
                aliases:
                    - host
        container_name: mysql_twitter
        restart: always
        
    server:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - custom_net
        container_name: server_twitter
        ports:
            - 22992:22992
        depends_on:
            - mysql
        restart: always

networks:
    custom_net:
        driver: bridge

